/**
 * ShopSphere — Master Seed Dataset
 * Realistic data for products, categories, demo users, inventory, and addresses.
 */

const CATEGORIES = [
  {
    name: 'Electronics & Audio',
    slug: 'electronics',
    description: 'High fidelity audio, smart gadgets, and cutting edge tech gear',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
  },
  {
    name: 'Wearables & Smartwatches',
    slug: 'wearables',
    description: 'Smart health trackers, premium wristwatches, and fitness rings',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
  },
  {
    name: 'Lifestyle & Apparel',
    slug: 'apparel',
    description: 'Premium everyday essentials, urban streetwear, and footwear',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800',
  },
  {
    name: 'Home & Workspace',
    slug: 'workspace',
    description: 'Minimalist desk gear, ergonomic chairs, and atmospheric lighting',
    imageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800',
  },
  {
    name: 'Photography & Optics',
    slug: 'photography',
    description: 'Mirrorless cameras, prime lenses, and studio accessories',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
  },
];

const PRODUCTS = [
  {
    sku: 'AUD-ANC-001',
    name: 'Aether Pro Wireless ANC Headphones',
    slug: 'aether-pro-wireless-anc-headphones',
    description: 'Engineered for audiophiles with 45mm beryllium drivers, active hybrid noise cancellation, 40-hour battery life, and ultra-plush memory foam earpads.',
    short_description: 'Premium hybrid noise cancelling wireless headphones with 40-hour battery.',
    categorySlug: 'electronics',
    brand: 'Aether Audio',
    price: 349.99,
    compare_at_price: 399.99,
    discount_percent: 12.5,
    is_featured: true,
    tags: ['wireless', 'noise-cancelling', 'bluetooth', 'audio', 'audiophile'],
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    stock: 75,
  },
  {
    sku: 'WRB-TITAN-002',
    name: 'Apex Horizon Titanium Smartwatch',
    slug: 'apex-horizon-titanium-smartwatch',
    description: 'Aircraft-grade titanium chassis, sapphire crystal display, ECG monitoring, dual-band GPS, and 100m water resistance for rugged outdoor expeditions.',
    short_description: 'Titanium chassis smartwatch with sapphire screen and 14-day battery.',
    categorySlug: 'wearables',
    brand: 'Apex',
    price: 499.00,
    compare_at_price: 549.00,
    discount_percent: 9.1,
    is_featured: true,
    tags: ['smartwatch', 'fitness', 'gps', 'titanium', 'waterproof'],
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
    stock: 45,
  },
  {
    sku: 'DESK-KB-003',
    name: 'KeyCraft Orbit CNC Mechanical Keyboard',
    slug: 'keycraft-orbit-cnc-mechanical-keyboard',
    description: 'Anodized aluminum body, hot-swappable tactile linear switches, south-facing RGB, customizable rotary encoder knob, and gasket mounted dampening.',
    short_description: 'Custom gasket-mounted mechanical keyboard with south-facing RGB.',
    categorySlug: 'workspace',
    brand: 'KeyCraft Studio',
    price: 219.99,
    compare_at_price: 250.00,
    discount_percent: 12.0,
    is_featured: true,
    tags: ['keyboard', 'mechanical', 'custom', 'desk-setup', 'usb-c'],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
    stock: 30,
  },
  {
    sku: 'OPT-CAM-004',
    name: 'Lumina X1 Full-Frame Mirrorless Body',
    slug: 'lumina-x1-full-frame-mirrorless-body',
    description: '33MP full-frame BSI sensor, 4K 60p 10-bit recording, AI subject tracking autofocus, and in-body 5-axis image stabilization.',
    short_description: '33MP full-frame mirrorless digital camera with 4K60p video.',
    categorySlug: 'photography',
    brand: 'Lumina Optical',
    price: 1899.99,
    compare_at_price: 2099.99,
    discount_percent: 9.5,
    is_featured: true,
    tags: ['camera', 'mirrorless', 'photography', '4k', 'video'],
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
    stock: 12,
  },
  {
    sku: 'LIF-BACKPACK-005',
    name: 'Vanguard Weatherproof Commuter Pack 24L',
    slug: 'vanguard-weatherproof-commuter-pack-24l',
    description: 'Constructed from X-Pac ripstop fabric with Fidlock magnetic buckles, dedicated 16-inch suspended laptop sleeve, and ergonomic air-mesh harness.',
    short_description: '24L waterproof urban commuter backpack with magnetic buckles.',
    categorySlug: 'apparel',
    brand: 'Vanguard Carry',
    price: 185.00,
    compare_at_price: 185.00,
    discount_percent: 0,
    is_featured: false,
    tags: ['backpack', 'commute', 'weatherproof', 'laptop-bag'],
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
    stock: 60,
  },
  {
    sku: 'AUD-EAR-006',
    name: 'Aether Pods Spatial ANC Earbuds',
    slug: 'aether-pods-spatial-anc-earbuds',
    description: 'True wireless spatial audio earbuds with active noise cancellation, transparency mode, wireless charging case, and IPX7 sweat resistance.',
    short_description: 'True wireless earbuds with spatial audio and wireless charging.',
    categorySlug: 'electronics',
    brand: 'Aether Audio',
    price: 179.99,
    compare_at_price: 199.99,
    discount_percent: 10.0,
    is_featured: false,
    tags: ['earbuds', 'wireless', 'anc', 'waterproof'],
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800',
    stock: 110,
  },
  {
    sku: 'DESK-LAMP-007',
    name: 'Halo Minimalist Aluminum Desk Screenbar',
    slug: 'halo-minimalist-aluminum-desk-screenbar',
    description: 'Precision asymmetrical optical design illuminating the workspace without screen glare. Touch controls for color temperature and brightness tuning.',
    short_description: 'Asymmetric monitor light bar with auto-dimming touch sensor.',
    categorySlug: 'workspace',
    brand: 'Halo Design',
    price: 89.00,
    compare_at_price: 99.00,
    discount_percent: 10.1,
    is_featured: false,
    tags: ['lighting', 'desk-setup', 'ergonomic', 'led'],
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
    stock: 8, // Low stock demo!
  },
  {
    sku: 'WRB-RING-008',
    name: 'Cirque Biomarker Smart Ring Gen 2',
    slug: 'cirque-biomarker-smart-ring-gen-2',
    description: 'Sleep stages analysis, HRV monitoring, body temperature tracking in an ultra-lightweight 4-gram titanium casing with 7-day battery life.',
    short_description: '4g titanium biometric sleep and health tracker ring.',
    categorySlug: 'wearables',
    brand: 'Cirque Labs',
    price: 299.00,
    compare_at_price: 329.00,
    discount_percent: 9.1,
    is_featured: true,
    tags: ['smart-ring', 'biometrics', 'sleep-tracker', 'titanium'],
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
    stock: 5, // Low stock demo!
  },
];

const SEED_USERS = [
  {
    email: 'admin@shopsphere.io',
    password: 'AdminPassword@123!',
    role: 'ADMIN',
    firstName: 'DevOps',
    lastName: 'Admin',
    phone: '+1 (555) 999-0001',
    address: {
      recipientName: 'DevOps Administrator',
      addressLine1: '100 Silicon Way',
      addressLine2: 'Suite 800',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94105',
      country: 'United States',
      phone: '+1 (555) 999-0001',
      isDefault: true,
    },
  },
  {
    email: 'customer@shopsphere.io',
    password: 'CustomerPassword@123!',
    role: 'CUSTOMER',
    firstName: 'Alex',
    lastName: 'Morgan',
    phone: '+1 (555) 444-1234',
    address: {
      recipientName: 'Alex Morgan',
      addressLine1: '456 Innovation Blvd',
      addressLine2: 'Apt 12B',
      city: 'Austin',
      state: 'TX',
      postalCode: '78701',
      country: 'United States',
      phone: '+1 (555) 444-1234',
      isDefault: true,
    },
  },
];

module.exports = {
  CATEGORIES,
  PRODUCTS,
  SEED_USERS,
};
